iceberg_spark:
  target: dev
  outputs:
    dev:
      type: spark
      method: http
      host: spark-thrift       # nombre del servicio en docker-compose
      port: 10000
      user: sparkuser
      http_path: cliservice
      schema: default          # dbt usa este como database base
      connect_retries: 5
      connect_timeout: 60
      threads: 4
